# lamp 
# httpd, mariadb105-server (mariadb), php (php-fpm)
---
- name: remove lamp in amazon linux
  hosts: localhost
  become: yes
  tasks: 
  # install httpd
  - name: remove httpd
    ansible.builtin.dnf:
     name: httpd
     state: absent
  # install maraiadb
  - name: remove mariadb package
    ansible.builtin.dnf:
     name: mariadb105-server
     state: absent
  # install php
  - name: remove php package
    ansible.builtin.dnf:
     name: 
      - php
      - php-fpm
     state: absent
  # start httpd
  - name: stop and disable httpd
    ansible.builtin.systemd_service:
     name: httpd
     state: stopped
     enabled: false
  # start mariadb
  - name: stop and disable mariadb
    ansible.builtin.systemd_service:
     name: mariadb
     state: stopped
     enabled: false
  # start php
  - name: stop and disable php
    ansible.builtin.systemd_service:
     name: php-fpm
     state: stopped
     enabled: false
  # deploy php
  - name: deploy php
    ansible.builtin.copy:
     dest: /var/www/html/index.php
     content: |
      <?php
      phpinfo();
      ?>


