# lamp 
# nginx, mariadb105-server (mariadb), php (php-fpm)
---
- name: install lamp in amazon linux
  hosts: localhost
  become: yes
  tasks: 
  # install nginx
  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: absent
  # install maraiadb
  - name: install mariadb package
    ansible.builtin.dnf:
     name: mariadb105-server
     state: absent
  # install php
  - name: install php package
    ansible.builtin.dnf:
     name: 
      - php
      - php-fpm
     state: absent
  # start nginx
  - name: start and enable nginx
    ansible.builtin.systemd_service:
     name: nginx
     state: started
     enabled: true
  # start mariadb
  - name: start and enabled mariadb
    ansible.builtin.systemd_service:
     name: mariadb
     state: started
     enabled: true
  # start php
  - name: start and enabled php
    ansible.builtin.systemd_service:
     name: php-fpm
     state: started
     enabled: true
  # deploy php
  - name: deploy php
    ansible.builtin.copy:
     dest: /usr/share/nginx/html/index.php
     content: | 
      <!DOCTYPE html>
      <html lang="en">
      <head>
      <meta charset="UTF-8">
      <title>Attractive Sample Web Page</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <style>
        body {
            margin: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: #333;
        }

        header {
            padding: 60px 20px;
            text-align: center;
            color: white;
        }

        header h1 {
            font-size: 42px;
            margin-bottom: 10px;
        }

        header p {
            font-size: 18px;
            opacity: 0.9;
        }

        .container {
            max-width: 1100px;
            margin: auto;
            padding: 40px 20px;
        }

        .cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }

        .card {
            background: white;
            padding: 25px;
            border-radius: 15px;
            box-shadow: 0 10px 25px rgba(0,0,0,0.15);
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .card:hover {
            transform: translateY(-8px);
            box-shadow: 0 15px 35px rgba(0,0,0,0.2);
        }

        .card h3 {
            margin-top: 0;
            color: #667eea;
        }

        .card p {
            font-size: 15px;
            line-height: 1.6;
        }

        .btn {
            display: inline-block;
            margin-top: 15px;
            padding: 10px 20px;
            background: #667eea;
            color: white;
            text-decoration: none;
            border-radius: 25px;
            font-size: 14px;
        }

        .btn:hover {
            background: #5563d6;
        }

        footer {
            background: #111;
            color: #aaa;
            text-align: center;
            padding: 20px;
            margin-top: 40px;
            font-size: 14px;
        }
       </style>
      </head>

      <body>

      <header>
       <h1>Welcome to My Website</h1>
       <p>Simple • Modern • Attractive Design</p>
        </header>

        <div class="container">
       <div class="cards">

        <div class="card">
            <h3>🚀 Fast Performance</h3>
            <p>Optimized design for fast loading and smooth user experience on all devices.</p>
            <a href="#" class="btn">Learn More</a>
        </div>

        <div class="card">
            <h3>🎨 Modern UI</h3>
            <p>Clean layout with modern colors, cards, and hover effects.</p>
            <a href="#" class="btn">View Design</a>
        </div>

        <div class="card">
            <h3>🔒 Secure</h3>
            <p>Best practices followed for security and reliability.</p>
            <a href="#" class="btn">Read More</a>
        </div>

         </div>
       </div>

      <footer>
       © 2025 MyWebsite | Designed with ❤️
       </footer>

       </body>
      <html>
      
      



