# install lemp 
---
- name: install lemp on target
  hosts: targetserver
  become: yes
  tasks:
  - name: install nginx, mariadb, php
    ansible.builtin.dnf:
     name:
      - httpd
      - mariadb105-server
      - php
      - php-fpm
     state: present
  - name: stop and disable nginx
    ansible.builtin.systemd_service:
     name: nginx 
     state: stopped
     enabled: false
  - name: start and enable nginx, mariadb, php
    ansible.builtin.systemd_service:
      name: "{{item}}"
      state: started
      enabled: true
    loop: 
     - httpd
     - mariadb
     - php-fpm
  - name: deploy php page
    ansible.builtin.copy:
     dest: /var/www/html/index.html
     content: |
      <h1> Welcome to my httpd website </h1>

