# variable -> dynamic value assigment
---
- name: install lamp in amazon linux
  hosts: localhost
  become: yes
  # define variable assign values
  vars: 
   web_pkg: nginx # hard coding
   db_pkg: mariadb105-server
   php_pkg:
    - php
    - php-fpm
   web_service: nginx
   db_service: mariadb
   php_service: php-fpm
   web_file_path: /usr/share/nginx/html/index.php
  tasks: 
  # install nginx
  - name: install nginx 
    ansible.builtin.dnf:
     name: "{{web_pkg}}"
     state: present
  # install mariadb
  - name: install mariadb
    ansible.builtin.dnf:
     name: "{{db_pkg}}"
     state: present
  # install php
  - name: install php-fpm
    ansible.builtin.dnf:
     name: "{{php_pkg}}"
     state: present
  # start nginx
  - name: start and enable
    ansible.builtin.systemd_service:
     name: "{{web_service}}"
     state: started
     enabled: true
  # start mariadb
  - name: start and enabled mariadb
    ansible.builtin.systemd_service:
     name: "{{db_service}}"
     state: started
     enabled: true
  # start php
  - name: start and enabled php
    ansible.builtin.systemd_service:
     name: "{{php_service}}"
     state: started
     enabled: true
  # deploy php
  - name: deploy php
    ansible.builtin.copy:
     dest: "{{web_file_path}}"
     content: | 
      <?php
      phpinfo();
      ?>