# install httpd using role concept
---
- name: install http using role
  hosts: localhost
  become: yes
  vars: 
    pkg: httpd
    svc: httpd
    file_path: /var/www/html/
  tasks: 
  # install httpd
  - name: install httpd
    ansible.builtin.dnf:
     name: "{{pkg}}"
     state: present 
  # start and enabled httpd
  - name: start and enabled httpd
    ansible.builtin.systemd_service:
     name: "{{svc}}"
     state: started
     enabled: true
  # deploy index.html
  - name: deploy index.html file
    ansible.builtin.copy:
     src: files/index.html
     dest: "{{file_path}}"
     